apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    tier: database
    project: roboshop
    environment: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: mongodb
      environment: dev
  template:
    metadata:
      labels:
        tier: mongodb
        environment: dev
    
    spec:
      containers:
      - name: mongodb
        image: surajk879/mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop

spec:
  selector:
    tier: database
    project: roboshop
    environment: dev
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017




