apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
  namespace: roboshop
  labels:
    tier: database
    project: roboshop
    environment: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        tier: database
        project: roboshop
        environment: dev
    spec:
      containers:
      - name: redis
        image: redis

---
apiVerison: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    tier: database
    project: roboshop
    environment: dev
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379